# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.10
      
    working_directory: /go/src/sour.is/x/toolbox

    steps:
      - checkout

      - run: mkdir -p $CIRCLE_TEST_REPORTS
      - run: go get github.com/jstemmer/go-junit-report

      - run: go get -v -t -d ./...
      - run: 
          name: Run unit tests
          command: |
            trap "go-junit-report <${CIRCLE_TEST_REPORTS}/go-test.out > ${CIRCLE_TEST_REPORTS}/go-test-report.xml" EXIT
            go test -v ./... | tee ${CIRCLE_TEST_REPORTS}/go-test.out

      - store_artifacts:
          path: $CIRCLE_TEST_REPORTS
          destination: raw-test-output

      - store_test_results:
          path: $CIRCLE_TEST_REPORTS
